apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: qddq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qddq
    app.kubernetes.io/part-of: byoc-app-ocdv
  name: qddqhxit
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: qddq
    weight: null
status: {}
